sudo: false
language: node_js
node_js:
  - v8
  - v6
script:
  - npm install -g codecov istanbul
  - npm test
  - istanbul cover _mocha
  - codecov
after_success:
- bash <(curl -s https://codecov.io/bash)